// <auto-generated />
namespace Repos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Migrn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migrn));
        
        string IMigrationMetadata.Id
        {
            get { return "202003300516180_Migrn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
